name: ".NET"
description: "Build, test, pack, and publish a .NET repository."
author: "bottlenoselabs"

inputs:
  repository:
    description: "The target repository."
    required: true
  dotnet-sdk-version:
    description: "The version of the .NET software development kit to use."
    required: true
  is-enabled-pack:
    description: "A boolean indicating wether to run `dotnet pack` and upload NuGet packages."
    required: true
  publish-environment:
    description: "The environment to use for releasing NuGet packages. 'staging' uses MyGet.org feed and 'release' uses NuGet.org feed."
    required: true
  myget-access-token:
    description: "The access token to upload NuGet packages to myget.org staging environment."
    required: true
  nuget-access-token:
    description: "The access token to upload NuGet packages to nuget.org release environment."
    required: true

runs:
  using: "composite"
  steps:

    - name: "Clone Git repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
        repository: '${{ inputs.repository }}'

    - name: "Install GitVersion"
      uses: gittools/actions/gitversion/setup@v0.9.6
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true # workaround for https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ until the execute action is updated
      with:
        versionSpec: '5.x'
          
    - name: "Execute GitVersion"
      uses: gittools/actions/gitversion/execute@v0.9.6

    - name: "Set version"
      id: version
      shell: bash
      run: echo "VERSION=$GITVERSION_NUGETVERSIONV2" >> $GITHUB_ENV

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ inputs.dotnet-sdk-version }}'
        include-prerelease: true

    - name: "Clean solution"
      shell: bash
      run: dotnet clean --verbosity quiet --configuration Release && dotnet nuget locals all --clear

    - name: "Build solution"
      shell: bash
      run: dotnet build --nologo --verbosity minimal --configuration Release /p:Version='${{ env.VERSION }}'

    - name: "Test solution"
      shell: bash
      run: dotnet test --nologo --verbosity minimal --configuration Release --no-build

    - name: "Pack solution"
      if: inputs.is-enabled-pack == 'true'
      shell: bash
      run: dotnet pack --nologo --verbosity minimal --configuration Release --no-build -p:PackageVersion='${{ env.VERSION }}'

    - name: "Staging"
      if: inputs.is-enabled-pack == 'true' && inputs.publish-environment == 'staging'
      shell: bash
      run: |
        echo "NUGET_SOURCE_URL=https://www.myget.org/F/bottlenoselabs/api/v3/index.json" >> $GITHUB_ENV
        echo "NUGET_ACCESS_TOKEN=${{ inputs.myget-access-token }}" >> $GITHUB_ENV

    - name: "Release"
      if: inputs.is-enabled-pack == 'true' && inputs.publish-environment == 'release'
      shell: bash
      run: |
        echo "NUGET_SOURCE_URL=https://api.nuget.org/v3/index.json" >> $GITHUB_ENV
        echo "NUGET_ACCESS_TOKEN=${{ inputs.nuget-access-token }}" >> $GITHUB_ENV

    - name: "Upload Packages"
      if: inputs.is-enabled-pack == 'true'
      shell: bash
      run: dotnet nuget push "./**/*.nupkg" --source $NUGET_SOURCE_URL --skip-duplicate --api-key $NUGET_ACCESS_TOKEN