name: ".NET"
description: "Build, test, pack, and publish a .NET repository."
author: "bottlenoselabs"

inputs:
  solution-or-project:
    description: "The target .NET solution (.sln) or C# project (.csproj)."
    required: false
    default: ''
  dotnet-sdk-version:
    description: "The version of the .NET software development kit to use."
    required: true
  is-enabled-pack:
    description: "A boolean indicating wether to run `dotnet pack` and upload NuGet packages."
    required: false
    default: 'false'
  upload-nuget-org:
    description: "Determines wether to upload to the NuGet.org feed."
    required: false
    default: 'false' #"${{ startsWith(github.ref, 'refs/tags/v') }}"
  upload-myget-org:
    description: "Determines wether to upload to the MyGet.org feed."
    required: false
    default: 'false' #"${{ github.event_name == 'push' || startsWith(github.ref, 'refs/tags/v') }}"
  myget-access-token:
    description: "The access token to upload NuGet packages to myget.org staging environment."
    required: true
  nuget-access-token:
    description: "The access token to upload NuGet packages to nuget.org release environment."
    required: true
  gitversion-working-directory:
    description: "GitVersion: Optionally supply the working directory."
    required: false
    default: '$(pwd)'
  gitversion-config-file-path:
    description: "GitVersion: Config file path."
    required: false
    default: 'GitVersion.yml'

runs:
  using: "composite"
  steps:

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ inputs.dotnet-sdk-version }}'
        include-prerelease: true

    - name: "Install GitVersion: Windows"
      if: runner.os == 'Windows'
      shell: bash
      run: '${{ github.action_path }}\scripts\install-gitversion.sh'

    - name: "Install GitVersion: Unix-like"
      if: runner.os != 'Windows'
      shell: bash
      run: '${{ github.action_path }}/scripts/install-gitversion.sh'

    - name: "GitVersion: Windows"
      if: runner.os == 'Windows'
      shell: bash
      run: '${{ github.action_path }}\scripts\gitversion.sh'

    - name: "GitVersion: Unix-like"
      if: runner.os != 'Windows'
      shell: bash
      run: '${{ github.action_path }}/scripts/gitversion.sh'

    - name: "GitVersion: Windows"
      if: runner.os == 'Windows'
      id: gitversion
      bash: shell
      run: |
        VERSION=$(${{ github.action_path }}\scripts\gitversion.sh)
        echo "::set-output name=version::$VERSION"

    - name: "GitVersion: Unix-like"
      if: runner.os != 'Windows'
      id: gitversion
      bash: shell
      run: |
        VERSION=$(${{ github.action_path }}/scripts/gitversion.sh)
        echo "::set-output name=version::$VERSION"

    - name: "Clean solution"
      shell: bash
      run: dotnet clean ${{ inputs.solution-or-project }} --verbosity quiet --configuration Release && dotnet nuget locals all --clear

    - name: "Build solution"
      shell: bash
      run: dotnet build ${{ inputs.solution-or-project }} --nologo --verbosity minimal --configuration Release -p:Version='${{ steps.gitversion.outputs.version }}'

    - name: "Test solution"
      shell: bash
      run: dotnet test ${{ inputs.solution-or-project }} --nologo --verbosity minimal --configuration Release --no-build

    - name: "Pack solution"
      shell: bash
      if: inputs.is-enabled-pack == 'true'
      run: dotnet pack ${{ inputs.solution-or-project }} --nologo --verbosity minimal --configuration Release --no-build -p:PackageVersion='${{ steps.gitversion.outputs.version }}'

    - name: "Upload Packages (MyGet)"
      shell: bash
      if: inputs.is-enabled-pack == 'true' && inputs.upload-myget-org == 'true'
      run: dotnet nuget push "./**/*.nupkg" --source https://www.myget.org/F/bottlenoselabs/api/v3/index.json --skip-duplicate --api-key ${{ inputs.myget-access-token }}

    - name: "Upload Packages (NuGet)"
      shell: bash
      if: inputs.is-enabled-pack == 'true' && inputs.upload-nuget-org == 'true'
      run: dotnet nuget push "./**/*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ inputs.nuget-access-token }}